"""empty message

Revision ID: 04de517162db
Revises: 9e8acd4a3bc0
Create Date: 2022-11-13 18:09:27.724088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04de517162db'
down_revision = '9e8acd4a3bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('pupil', 'dob')
    op.drop_column('pupil', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('date', sa.VARCHAR(length=50), nullable=False))
    op.add_column('pupil', sa.Column('dob', sa.DATETIME(), nullable=True))
    op.drop_column('pupil', 'age')
    # ### end Alembic commands ###
