"""empty message

Revision ID: 106a0c265134
Revises: 67081c794a98
Create Date: 2022-11-10 22:52:11.379438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '106a0c265134'
down_revision = '67081c794a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    op.add_column('teller', sa.Column('ref_number', sa.LargeBinary(), nullable=True))
    op.add_column('teller', sa.Column('trans_key', sa.LargeBinary(), nullable=True))
    op.add_column('teller', sa.Column('trans_id', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'teller', ['trans_id'])
    op.create_unique_constraint(None, 'teller', ['trans_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teller', type_='unique')
    op.drop_constraint(None, 'teller', type_='unique')
    op.drop_column('teller', 'trans_id')
    op.drop_column('teller', 'trans_key')
    op.drop_column('teller', 'ref_number')
    op.create_table('keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ref_number', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('trans_key', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('trans_id', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('teller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teller_id'], ['teller.id'], name='keys_teller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='keys_pkey'),
    sa.UniqueConstraint('trans_id', name='keys_trans_id_key'),
    sa.UniqueConstraint('trans_key', name='keys_trans_key_key')
    )
    # ### end Alembic commands ###
