"""empty message

Revision ID: 14a2740fd616
Revises: 5f207c11218b
Create Date: 2022-11-10 22:33:46.196808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a2740fd616'
down_revision = '5f207c11218b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('teller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'account', 'teller', ['teller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'teller_id')
    # ### end Alembic commands ###
