"""empty message

Revision ID: 177ec173844f
Revises: 
Create Date: 2022-11-06 23:16:05.218674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177ec173844f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('trans_key', sa.LargeBinary(), nullable=True))
    op.add_column('account', sa.Column('trans_id', sa.LargeBinary(), nullable=True))
    op.add_column('teller', sa.Column('ref_number', sa.LargeBinary(), nullable=True))
    op.drop_column('teller', 'unique_digits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teller', sa.Column('unique_digits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('teller', 'ref_number')
    op.drop_column('account', 'trans_id')
    op.drop_column('account', 'trans_key')
    # ### end Alembic commands ###
