"""empty message

Revision ID: 63da8339572f
Revises: 7f226fb80239
Create Date: 2022-11-05 10:14:09.257888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63da8339572f'
down_revision = '7f226fb80239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('parent_name', sa.String(length=120), nullable=True))
    op.add_column('pupil', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('pupil', sa.Column('dob', sa.DateTime(), nullable=True))
    op.drop_column('pupil', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pupil', 'dob')
    op.drop_column('pupil', 'address')
    op.drop_column('pupil', 'parent_name')
    # ### end Alembic commands ###
