"""empty message

Revision ID: 67081c794a98
Revises: 14a2740fd616
Create Date: 2022-11-10 22:43:51.486534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67081c794a98'
down_revision = '14a2740fd616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_teller_id_fkey', 'account', type_='foreignkey')
    op.drop_column('account', 'teller_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('teller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('account_teller_id_fkey', 'account', 'teller', ['teller_id'], ['id'])
    # ### end Alembic commands ###
