"""empty message

Revision ID: 8e0a40348788
Revises: 203a4f602dd0
Create Date: 2022-11-04 16:55:52.764679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0a40348788'
down_revision = '203a4f602dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'school_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('account', 'pupil_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('pupil', 'school_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('teller', 'school_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teller', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pupil', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'pupil_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
