"""empty message

Revision ID: a50a23aa5026
Revises: 177ec173844f
Create Date: 2022-11-06 23:31:14.660550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50a23aa5026'
down_revision = '177ec173844f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['trans_key'])
    op.create_unique_constraint(None, 'account', ['trans_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
