"""empty message

Revision ID: dea514d1ffe9
Revises: 8e0a40348788
Create Date: 2022-11-04 16:59:03.929653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea514d1ffe9'
down_revision = '8e0a40348788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'school_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('account', 'pupil_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('pupil', 'school_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.add_column('school', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('teller', 'school_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teller', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('school', 'email')
    op.alter_column('pupil', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'pupil_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
